featureFlags:
  flags:
  - flag:
      name: qq
      identifier: qq
      description: ""
      permanent: false
      spec:
        type: boolean
        default:
          onVariation: "true"
          offVariation: "false"
        variations:
        - identifier: "true"
          value: "true"
        - identifier: "false"
          value: "false"
      environments:
      - identifier: qqq
        default:
          onVariation: "true"
          offVariation: "false"
        state: "off"
        targetRules:
        - targets:
          - identifier: ios
          variation: "true"
  projectIdentifier: crystaltest
  orgIdentifier: default
